### ISSUE TITLE
icons don't work on homepage

### ISSUE THREAD

**Issue by atilkan** [buefy/buefy#767]
Macosx
Chrome
![screen shot 2018-04-14 at 19 25 55](https://user-images.githubusercontent.com/1254613/38770313-c649f908-4019-11e8-83c4-eb0c0e3ac492.png)

**Comment by philipithomas** [comment]
This seems fixed now?

**Comment by adriaanmeuris** [comment]
No:
<img width="229" alt="screenshot 2018-12-06 at 14 15 40" src="https://user-images.githubusercontent.com/16230038/49586503-a2023e00-f961-11e8-8618-9e9c53f3390e.png">

Example iconfont link:
https://buefy.github.io/static/fonts/fa-solid-900.06a7df4.ttf

404 on all iconfonts:
<img width="634" alt="screenshot 2018-12-06 at 14 16 07" src="https://user-images.githubusercontent.com/16230038/49586538-ba725880-f961-11e8-90dd-5e5f2819c85a.png">

Filenames should be updated to [match these](https://github.com/buefy/buefy.github.io/tree/master/static/fonts) I guess?

**Comment by atilkan** [comment]
@jtommy It works for me now.

**Comment by adriaanmeuris** [comment]
@jtommy: yes, I have caching disabled using Chrome DevTools. Empty cache and hard reload doesn't resolve either
![kapture 2018-12-10 at 8 58 49](https://user-images.githubusercontent.com/16230038/49718317-040cbd00-fc5a-11e8-939b-76411d997722.gif)

**Comment by jtommy** [comment]
Try without #, thanks.

**Comment by adriaanmeuris** [comment]
Same thing. Homepage references [this css file](https://buefy.github.io/static/css/app.113065ab043d8103ccf8c1658448aad3.css), which links to e.g. [this reference to fa-regular](https://buefy.github.io/static/fonts/fa-regular-400.5e3bdde.woff) which 404's
